### PR TITLE
add storybook tests for BreakpointProvider

### PR DESCRIPTION
**Pull request by garetmckinley**
- add test for `Default breakpoints`
- add test for Bootstrap 3 breakpoints

### CODE REVIEW

**Comment by garetmckinley** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://f0319018-fdb0-402f-ac25-15fe9755e3bd.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/JSBros/hedron/branch/breakpoint-provider-tests/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by garetmckinley** [comment]
@nathanielpiche I put up [two basic storybook tests](https://3c92a6cb-8dc3-420f-8183-2c2510112520.sbook.io/) for the `BreakpointProvider`. If you can think of any other useful tests that we can implement in the storybook, let me know! I wasn't sure what the most useful way to visually test breakpoints was, so I'd appreciate any input you have 😄 

I'm also thinking about improving the `debug` mode for breakpoints. Something along the lines of throwing an `::after` pseudo element in the top-right of each `Column` that displays the current breakpoint it's using. Maybe also do the same thing for the `Page` component, but instead of showing the current breakpoint, the `Page` component would display the current view size. That way you could quickly tell if it's breaking when it's supposed to break.

**Comment by nathanielpiche** [comment]
Pretty straightforwards tests.
👍 for the debug improvements. 
Should we add a story showcasing `withBreakpoints`?

**Comment by garetmckinley** [comment]
Sure! Any idea what to demonstrate on that story?

**Comment by nathanielpiche** [comment]
Here is what I can think of:
* Displaying the current breakpoints.
* Two sets of breakpoints in the same page?
* Dynamic breakpoints?

I can't really see the usefulness (_is that a word?_) of the last two though.

**Comment by garetmckinley** [comment]
I don't personally see the value in the last two either, but I'm sure there's some edge case where it would be useful. I'll add them to the storybook :+1:

**Pull request merged**
